export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SET_SYSTEM_MESSAGE = 'SET_SYSTEM_MESSAGE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'

export const SET_PRIVATE_MODE = 'SET_PRIVATE_MODE'
export const SET_PRIVATE_RECIPIENTS = 'SET_PRIVATE_RECIPIENTS'
export const SET_AUTHORS = 'SET_AUTHORS'
export const SET_AUTHOR_COLOR = 'SET_AUTHOR_COLOR'
export const SET_ME = 'SET_ME'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RUN_COMMAND = 'RUN_COMMAND'
